window.ETAPPENINFO = {
   "01 Steeg-Weissenbach.gpx": {
      "Titel": "Biketrail-Etappe 1: Steeg-Weissenbach",
      "Ausgangspunkt": "Steeg",
      "Endpunkt": "Weissenbach",
      "Laenge": "44",
      "Fahrzeit": "4,5",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "200",
      "Hoehenmeterab": "420",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-steeg-weissenbach"
   },
   "02 Weissenbach-Tannheim.gpx": {
      "Titel": "Biketrail-Etappe 2: Weissenbach-Tannheim",
      "Ausgangspunkt": "Weissenbach",
      "Endpunkt": "Tannheim",
      "Laenge": "17,1",
      "Fahrzeit": "2,25",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "400",
      "Hoehenmeterab": "190",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-weissenbach-tannheim"
   },
   "03 Tannheim-Reutte.gpx": {
      "Titel": "Biketrail-Etappe 3: Tannheim-Reutte",
      "Ausgangspunkt": "Tannheim",
      "Endpunkt": "Reutte",
      "Laenge": "44",
      "Fahrzeit": "4",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "500",
      "Hoehenmeterab": "590",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-tannheim-reutte"
   },
   "04 Weissenbach-Reutte.gpx": {
      "Titel": "Biketrail-Etappe 4: Weissenbach-Reutte",
      "Ausgangspunkt": "Weissenbach",
      "Endpunkt": "Reutte",
      "Laenge": "7,1",
      "Fahrzeit": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "160",
      "Hoehenmeterab": "50",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-weissenbach-reutte"
   },
   "05 Reutte-Ehrwald.gpx": {
      "Titel": "Biketrail-Etappe 5: Reutte-Ehrwald",
      "Ausgangspunkt": "Reutte",
      "Endpunkt": "Ehrwald",
      "Laenge": "18,8",
      "Fahrzeit": "2",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "280",
      "Hoehenmeterab": "285",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-reutte-ehrwald"
   },
   "06 Ehrwald-Scharnitz.gpx": {
      "Titel": "Biketrail-Etappe 6: Ehrwald-Scharnitz",
      "Ausgangspunkt": "Ehrwald",
      "Endpunkt": "Scharnitz",
      "Laenge": "40",
      "Fahrzeit": "4",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "990",
      "Hoehenmeterab": "1200",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-ehrwald-scharnitz"
   },
   "07 Scharnitz-Achensee.gpx": {
      "Titel": "Biketrail-Etappe 7: Scharnitz - Achensee",
      "Ausgangspunkt": "Scharnitz",
      "Endpunkt": "Achensee",
      "Laenge": "61,5",
      "Fahrzeit": "6",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1850",
      "Hoehenmeterab": "1880",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-scharnitz-achensee"
   },
   "08 Achensee-Kaiserhaus.gpx": {
      "Titel": "Biketrail-Etappe 8: Achensee - Kaiserhaus",
      "Ausgangspunkt": "Achensee",
      "Endpunkt": "Kaiserhaus",
      "Laenge": "56",
      "Fahrzeit": "5",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1460",
      "Hoehenmeterab": "1660",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-achensee-kaiserhaus"
   },
   "09 Kaiserhaus-Kufstein.gpx": {
      "Titel": "Biketrail-Etappe 9: Kaiserhaus � Kufstein ",
      "Ausgangspunkt": "Kaiserhaus",
      "Endpunkt": "Kufstein",
      "Laenge": "31,5",
      "Fahrzeit": "3,25",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "540",
      "Hoehenmeterab": "780",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-kaiserhaus-kufstein"
   },
   "10 Kufstein-Koessen.gpx": {
      "Titel": "Biketrail-Etappe 10: Kufstein - Koessen ",
      "Ausgangspunkt": "Kufstein",
      "Endpunkt": "Kössen",
      "Laenge": "33,8",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "770",
      "Hoehenmeterab": "660",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-kufstein-koessen"
   },
   "11 Koessen-Kitzbuehel.gpx": {
      "Titel": "Biketrail-Etappe 11: Koessen - Kitzbuehel",
      "Ausgangspunkt": "Kössen",
      "Endpunkt": "Kitzbühel",
      "Laenge": "56",
      "Fahrzeit": "7",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1900",
      "Hoehenmeterab": "1730",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-koessen-kitzbuehel"
   },
   "12 Variante Pillersee.gpx": {
      "Titel": "Biketrail-Etappe 12: Variante Pillersee ",
      "Ausgangspunkt": "Erpfendorf",
      "Endpunkt": "Mühlbach",
      "Laenge": "42",
      "Fahrzeit": "4",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "850",
      "Hoehenmeterab": "770",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-variante-pillersee"
   },
   "13 Kitzbühel-Westendorf.gpx": {
      "Titel": "Biketrail-Etappe 13: Kitzbuehel - Westendorf ",
      "Ausgangspunkt": "Kitzbühel",
      "Endpunkt": "Westendorf",
      "Laenge": "15,5",
      "Fahrzeit": "1,75",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "150",
      "Hoehenmeterab": "150",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-kitzbuehel-westendorf"
   },
   "14 Westendorf-Alpbach.gpx": {
      "Titel": "Biketrail-Etappe 14: Westendorf - Alpbach ",
      "Ausgangspunkt": "Westendorf",
      "Endpunkt": "Alpbach",
      "Laenge": "36,5",
      "Fahrzeit": "4,5",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "1300",
      "Hoehenmeterab": "1100",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-westendorf-alpbach"
   },
   "15 Alpbach-Zell.gpx": {
      "Titel": "Biketrail-Etappe 15: Alpbach- Zell",
      "Ausgangspunkt": "Alpbach",
      "Endpunkt": "Zell",
      "Laenge": "43,5",
      "Fahrzeit": "5",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "1150",
      "Hoehenmeterab": "1550",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-alpbach-zell"
   },
   "16 Zell-Achensee.gpx": {
      "Titel": "Biketrail-Etappe 16: Zell - Achensee ",
      "Ausgangspunkt": "Zell",
      "Endpunkt": "Achensee",
      "Laenge": "36,5",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "580",
      "Hoehenmeterab": "220",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-zell-achensee"
   },
   "17 Zell-Mayrhofen.gpx": {
      "Titel": "Biketrail-Etappe 17: Zell - Mayrhofen ",
      "Ausgangspunkt": "Zell",
      "Endpunkt": "Mayrhofen",
      "Laenge": "8,8",
      "Fahrzeit": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "30",
      "Hoehenmeterab": "90",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-zell-mayrhofen"
   },
   "18 Mayrhofen-Lanersbach.gpx": {
      "Titel": "Biketrail-Etappe 18: Mayrhofen - Lanersbach ",
      "Ausgangspunkt": "Mayrhofen",
      "Endpunkt": "Lanersbach",
      "Laenge": "14,5",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "900",
      "Hoehenmeterab": "280",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-mayrhofen-lanersbach"
   },
   "19 Lanersbach-Weerberg.gpx": {
      "Titel": "Biketrail-Etappe 19: Lanersbach - Geiseljoch - Weerberg ",
      "Ausgangspunkt": "Lanersbach",
      "Endpunkt": "Weerberg",
      "Laenge": "28",
      "Fahrzeit": "5",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1090",
      "Hoehenmeterab": "1480",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-lanersbach-geiseljoch-weerberg"
   },
   "20 Weerberg-Windegg.gpx": {
      "Titel": "Biketrail-Etappe 20: Weerberg - Windegg",
      "Ausgangspunkt": "Weerberg",
      "Endpunkt": "Windegg",
      "Laenge": "22",
      "Fahrzeit": "4,5",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "940",
      "Hoehenmeterab": "630",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-weerberg-windegg"
   },
   "21 Windegg-Matrei.gpx": {
      "Titel": "Biketrail-Etappe 21: Windegg - Matrei",
      "Ausgangspunkt": "Windegg",
      "Endpunkt": "Matreier Tauernhaus",
      "Laenge": "27",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "520",
      "Hoehenmeterab": "720",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-windegg-matrei"
   },
   "22 Matrei-Mieders.gpx": {
      "Titel": "Biketrail-Etappe 22: Matrei - Mieders",
      "Ausgangspunkt": "Matrei",
      "Endpunkt": "Mieders",
      "Laenge": "13",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "740",
      "Hoehenmeterab": "740",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-matrei-maria-waldrast-mieders"
   },
   "23 Mieders-Mutters.gpx": {
      "Titel": "Biketrail-Etappe 23: Mieders - Mutters ",
      "Ausgangspunkt": "Mieders",
      "Endpunkt": "Mutters",
      "Laenge": "20",
      "Fahrzeit": "2",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "900",
      "Hoehenmeterab": "1030",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-mieders-mutters"
   },
   "24 Mutters-Sellrain.gpx": {
      "Titel": "Biketrail-Etappe 24: Mutters - Sellrain ",
      "Ausgangspunkt": "Mutters",
      "Endpunkt": "Sellrain",
      "Laenge": "16,7",
      "Fahrzeit": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "415",
      "Hoehenmeterab": "310",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-mutters-sellrain"
   },
   "25 Sellrain-Oetz.gpx": {
      "Titel": "Biketrail-Etappe 25: Sellrain - Kuehtai - Oetz ",
      "Ausgangspunkt": "Sellrain",
      "Endpunkt": "Ötz",
      "Laenge": "34,6",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "1110",
      "Hoehenmeterab": "1270",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-sellrain-kuehtai-oetz"
   },
   "26 Oetz-Imst.gpx": {
      "Titel": "Biketrail-Etappe 26: Oetz - Imst",
      "Ausgangspunkt": "Ötz",
      "Endpunkt": "Imst",
      "Laenge": "14,6",
      "Fahrzeit": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeterauf": "215",
      "Hoehenmeterab": "280",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-oetz-imst"
   },
   "27 Imst-Wenns.gpx": {
      "Titel": "Biketrail-Etappe 27: Imst - Venetalm - Wenns ",
      "Ausgangspunkt": "Imst",
      "Endpunkt": "Wenns",
      "Laenge": "21,9",
      "Fahrzeit": "2",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1230",
      "Hoehenmeterab": "965",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-imst-venetalm-wenns"
   },
   "28 Wenns-Landeck.gpx": {
      "Titel": "Biketrail-Etappe 28: Wenns - Pillerhoehe - Landeck ",
      "Ausgangspunkt": "Wenns",
      "Endpunkt": "Landeck",
      "Laenge": "18,7",
      "Fahrzeit": "1",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "630",
      "Hoehenmeterab": "880",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-wenns-pillerhoehe-landeck"
   },
   "29 Landeck-Ischgl.gpx": {
      "Titel": "Biketrail-Etappe 29: Landeck - Ischgl ",
      "Ausgangspunkt": "Landeck",
      "Endpunkt": "Ischgl",
      "Laenge": "33",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1250",
      "Hoehenmeterab": "690",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-landeck-ischgl"
   },
   "30 Ischgl-St.Anton.gpx": {
      "Titel": "Biketrail-Etappe 30: Ischgl - St. Anton ",
      "Ausgangspunkt": "Ischgl",
      "Endpunkt": "St. Anton",
      "Laenge": "41,8",
      "Fahrzeit": "4",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1290",
      "Hoehenmeterab": "1200",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-ischgl-st-anton"
   },
   "31 St.Anton-Steeg.gpx": {
      "Titel": "Biketrail-Etappe 31: St. Anton - Steeg ",
      "Ausgangspunkt": "St. Anton",
      "Endpunkt": "Steeg",
      "Laenge": "35,1",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeterauf": "750",
      "Hoehenmeterab": "1080",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-st-anton-steeg"
   },
   "32 Imst-Ehrwald.gpx": {
      "Titel": "Biketrail-Etappe 32: Imst - Marienbergjoch - Ehrwald ",
      "Ausgangspunkt": "Imst",
      "Endpunkt": "Ehrwald",
      "Laenge": "37,1",
      "Fahrzeit": "3",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeterauf": "1380",
      "Hoehenmeterab": "1100",
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-imst-marienbergjoch-ehrwald"
   }
};